### ISSUE TITLE
Points Types admin screen: better meta boxes compatibility

### ISSUE THREAD

**Issue by JDGrimes** [WordPoints/wordpoints#765]
I've received a report from a user about a compatibility issue with the [WCMp plugin](https://wordpress.org/plugins/dc-woocommerce-multi-vendor/). When visiting the points types admin screen, the following error would occur:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function WCMp_Admin::adding_vendor_application_meta_boxes(), 1 passed in /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /Applications/AMPPS/www/gauge/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-admin.php:52 Stack trace: #0 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(286): WCMp_Admin->adding_vendor_application_meta_boxes(\'wordpoints_page...\') 
#1 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#2 /Applications/AMPPS/www/gauge/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#3 /Applications/AMPPS/www/gauge/wp-content/plugins/wordpoints/components/points/admin/classes/screen/points/types.php(642): do_action(\'add_meta_boxes\', \'wordpoints_page...\') 
#4 /Applications/AMPPS/www/gauge/wp-includes/class-wp-hook.php(286): WordPoints_Points_Admin_Screen_Points_Types->load(\'\') 
#5 /Applications/AMPPS/www/gauge/wp-includes/class in /Applications/AMPPS/www/gauge/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-wcmp-admin.php on line 52
```

In essence, what is happening here is that we are using the meta boxes API in an unexpected manner (though not necessarily in a wrong manner). The WCMp plugin is expecting two values to be passed, while we are only passing one. We can't pass an actual post ID as it would usually expect, but we can avoid a fatal error (and indeed, any error), by passing null.

**Comment by JDGrimes** [comment]
A conflict had also been reported with the [PayPal for WooCommerce plugin](https://wordpress.org/plugins/paypal-for-woocommerce/), and this fixes that conflict as well.
